elifesciences/sciencebeam-trainer-delft

sciencebeam_trainer_delft/preprocess.py, sciencebeam_trainer_delft/trainer.py, sciencebeam_trainer_delft/utils.py, sciencebeam_trainer_delft/wrapper.py, tests/grobid_trainer_test.py, tests/preprocess_test.py
fix for #16 having broken train_eval and nfold
=> fix eval with features

sciencebeam_trainer_delft/embedding_manager.py, sciencebeam_trainer_delft/grobid_trainer.py
=> fixed use of download manager for embedding

docker-compose.yml
the path has changed which wasn't reflected in the docker compose config
=> fixed data volume path

.pylintrc, Makefile, sciencebeam_trainer_delft/callbacks.py, sciencebeam_trainer_delft/cloud_support.py, sciencebeam_trainer_delft/config.py, sciencebeam_trainer_delft/grobid_trainer.py, sciencebeam_trainer_delft/preprocess.py, sciencebeam_trainer_delft/saving.py, sciencebeam_trainer_delft/trainer.py, sciencebeam_trainer_delft/utils.py, sciencebeam_trainer_delft/wrapper.py
now saving (as per final model):
- preprocessor
- model config
- model weights
as well as:
- meta which includes for example epoch, loss and learning rate (the latter for resuming models)
- add entry to checkpoint reference to easily find the latest epoch
=> save model config together with checkpoint weights etc

sciencebeam_trainer_delft/reader.py, tests/reader_test.py
=> added load_data_crf_string

.gitignore, Dockerfile, Makefile, config/embedding-registry.json, sciencebeam_trainer_delft/download_manager.py, sciencebeam_trainer_delft/embedding_manager.py, sciencebeam_trainer_delft/grobid_trainer.py, sciencebeam_trainer_delft/wrapper.py, tests/download_manager_test.py, tests/embedding_manager_test.py
This will allow embeddings to be automatically downloaded based on the saved model config.
=> download embeddings via registry

Jenkinsfile
=> fixed push unstable grobid image

sciencebeam_trainer_delft/utils/no_warn_if_disabled.py, sciencebeam_trainer_delft/utils/warnings.py
allows one to explicitly hide warnings (e.g. in a notebook)
=> added hide_warnings

Dockerfile.grobid, docker-compose.yml
remove `libjep.so` as it's incompatible with the virtual environment.
=> fix grobid jep

Dockerfile.jupyter
part of part of https://github.com/elifesciences/issues/issues/5299
=> removed python2 from project

sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py
this will be more in line with upstream delft
=> use input as full evaluation set by default

README.md, sciencebeam_trainer_delft/sequence_labelling/debug.py, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/saving.py, sciencebeam_trainer_delft/sequence_labelling/tag_formatter.py, sciencebeam_trainer_delft/sequence_labelling/tagger.py, tests/sequence_labelling/debug_test.py, tests/sequence_labelling/tag_formatter_test.py
this helps to visualize what the tagging output actually looks like
=> format tag output

README.md, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/tag_formatter.py, tests/sequence_labelling/tag_formatter_test.py
This makes it easier to quickly see the difference between expected and predicted labels.
=> added tag_diff

sciencebeam_trainer_delft/sequence_labelling/data_generator.py, tests/sequence_labelling/data_generator_test.py
apply fix for https://github.com/kermitt2/delft/issues/44
=> apply fix max sequence length

Makefile, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/utils/cli.py
this helps to make arguments be defined only for particular sub commands (e.g. tag output format)
=> use sub command

sciencebeam_trainer_delft/sequence_labelling/data_generator.py, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, tests/sequence_labelling/data_generator_test.py
#142 was missing truncating batch_y
=> fixed max sequence length implementation

README.md, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/utils/no_keras_backend_message.py
especially useful for the tag sub-command
=> added --quiet flag

README.md, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py
rather than using a slice of the training data, optionally use separate evaluation data
=> allow evaluation data to be passed in to train_eval

sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/tagger.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py
=> pass in separate max length for tagging, none by default

sciencebeam_trainer_delft/sequence_labelling/tools/install_models.py, tests/sequence_labelling/tools/install_models_test.py
resolves https://github.com/elifesciences/issues/issues/5498
=> fixed install gzipped wapiti model

sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py
this is to also experiment with models such as the `segmentation` model
=> extended grobid model list

README.md, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/input_info.py
this is useful as the features depend on the input data and this makes it easier to identify which ones to use.
(e.g. for the `segmentation` model it seems to be `6-23,27-31`)
=> show suggested feature indices

sciencebeam_trainer_delft/sequence_labelling/engines/wapiti.py, sciencebeam_trainer_delft/sequence_labelling/engines/wapiti_adapters.py, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py
the default values match [GROBID's WapitiTrainer](https://github.com/kermitt2/grobid/blob/0.5.6/grobid-trainer/src/main/java/org/grobid/trainer/WapitiTrainer.java#L20-L21).
=> make more wapiti arguments configurable

README.md, sciencebeam_trainer_delft/sequence_labelling/engines/wapiti.py, sciencebeam_trainer_delft/sequence_labelling/engines/wapiti_adapters.py
The results were not as reliable (evaluation always zero). This is now just labelling via the wapiti cli which looks better.
=> fixed wapiti tag and evaluation

sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, tests/sequence_labelling/grobid_trainer_test.py
the previous wapiti integration wasn't tested well enough..
=> fixed loading delft model

sciencebeam_trainer_delft/sequence_labelling/engines/wapiti_adapters.py, sciencebeam_trainer_delft/sequence_labelling/evaluation.py, sciencebeam_trainer_delft/sequence_labelling/trainer.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py
otherwise the labels were in a random order which makes it more difficult to compare the results (in the absence of a machine readable report)
=> sort evaluation report

README.md, sciencebeam_trainer_delft/sequence_labelling/config.py, sciencebeam_trainer_delft/sequence_labelling/data_generator.py, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/models.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py, tests/sequence_labelling/data_generator_test.py, tests/sequence_labelling/grobid_trainer_test.py, tests/sequence_labelling/models_test.py
resolves https://github.com/elifesciences/issues/issues/5538
=> optionally disable word embeddings

sciencebeam_trainer_delft/sequence_labelling/engines/wapiti_adapters.py, tests/sequence_labelling/engines/wapiti_adapters_test.py
Part of https://github.com/elifesciences/issues/issues/5571
=> use grobid label scheme for wapiti

README.md, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/utils/io.py, sciencebeam_trainer_delft/utils/logging.py, tests/grobid/import_test.py, tests/utils/logging_test.py
Resolves https://github.com/elifesciences/issues/issues/5575
Add `--save-file` option which can be a cloud source.
=> optionally save output to log file

README.md, sciencebeam_trainer_delft/sequence_labelling/engines/wapiti_adapters.py, sciencebeam_trainer_delft/sequence_labelling/evaluation.py, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/trainer.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py, sciencebeam_trainer_delft/utils/io.py, tests/sequence_labelling/evaluation_test.py
resolves https://github.com/elifesciences/issues/issues/5578
evaluation can now be output as JSON and also saved to a file
=> machine readable evaluation

README.md, sciencebeam_trainer_delft/sequence_labelling/engines/wapiti_adapters.py, sciencebeam_trainer_delft/sequence_labelling/evaluation.py, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/tools/checkpoints.py, sciencebeam_trainer_delft/sequence_labelling/utils/train_notify.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py, tests/sequence_labelling/utils/train_notify_test.py
resolves https://github.com/elifesciences/issues/issues/5576
=> optionally send notification when training completes

README.md, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py
extension of #193 (see https://github.com/elifesciences/issues/issues/5576)
=> notification url now also supported for wapiti train commands

README.md, sciencebeam_trainer_delft/sequence_labelling/config.py, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/trainer.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py
Training failed with out of memory after many epochs. This change will allow resume training from the last checkpoint.
=> resume training

README.md, sciencebeam_trainer_delft/sequence_labelling/tools/install_models.py, sciencebeam_trainer_delft/utils/io.py, tests/sequence_labelling/tools/install_models_test.py
This allows compressed files to be installed, which also enables installing models via http.
=> added tar gz and zip support for override models

README.md, sciencebeam_trainer_delft/sequence_labelling/config.py, sciencebeam_trainer_delft/sequence_labelling/data_generator.py, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/tagger.py, sciencebeam_trainer_delft/sequence_labelling/trainer.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py, tests/sequence_labelling/data_generator_test.py, tests/sequence_labelling/grobid_trainer_test.py
=> added --text-feature-indices support

sciencebeam_trainer_delft/sequence_labelling/data_generator.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py, tests/sequence_labelling/data_generator_test.py
should also re-use the code when doing the batch data generation
=> added iter_batch_text_list to reduce memory for preprocessor

README.md, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py
allows to increase the char lstm units (among other parameters that are already internally configurable)
=> expose more train config

sciencebeam_trainer_delft/sequence_labelling/wrapper.py
especially without then selecting feature indicies that preprocessor can get quite large
=> don't create features preprocessor if not used

requirements.txt
build is currently failing with lmdb 1.0.0
=> downgraded lmdb to 0.9.9

README.md, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/models.py, sciencebeam_trainer_delft/sequence_labelling/tagger.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py, sciencebeam_trainer_delft/utils/misc.py, tests/conftest.py, tests/sequence_labelling/grobid_trainer_test.py, tests/sequence_labelling/tagger_test.py, tests/utils/misc_test.py
part of https://github.com/elifesciences/issues/issues/6057
=> implemented sliding windows when tagging

README.md, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py
part of https://github.com/elifesciences/issues/issues/6057
this also allows sliding windows to be used for the low level evaluation (not n-fold yet).
=> implemented eval with sliding windows

notebooks/train-header.ipynb, requirements.cpu.txt
part of https://github.com/elifesciences/issues/issues/6132
=> upgraded tensorflow to 1.15.4

Dockerfile, requirements.txt, sciencebeam_trainer_delft/sequence_labelling/wrapper.py, sciencebeam_trainer_delft/utils/io.py, tests/sequence_labelling/grobid_trainer_test.py
part of https://github.com/elifesciences/sciencebeam-issues/issues/67
=> fix bad conversion

README.md
after switching to using pyenv locally, this provides some extra information to get it working.
=> added prerequisites relating to pyenv

sciencebeam_trainer_delft/utils/progress_logger.py, tests/utils/progress_logger_test.py
see also https://github.com/elifesciences/sciencebeam-utils/pull/129
=> fixed progress logger with newer version of tqdm

README.md, sciencebeam_trainer_delft/sequence_labelling/models.py, sciencebeam_trainer_delft/sequence_labelling/reader.py, sciencebeam_trainer_delft/sequence_labelling/saving.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/cli.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/cli_args.py, sciencebeam_trainer_delft/sequence_labelling/transfer_learning.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py, sciencebeam_trainer_delft/utils/misc.py, tests/sequence_labelling/tools/grobid_trainer/utils_test.py, tests/sequence_labelling/transfer_learning_test.py, tests/sequence_labelling/wrapper_test.py, tests/utils/misc_test.py
part of https://github.com/elifesciences/sciencebeam-issues/issues/108
=> added transfer learning

README.md, sciencebeam_trainer_delft/sequence_labelling/config.py, sciencebeam_trainer_delft/sequence_labelling/models.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/cli.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/cli_args.py
part of https://github.com/elifesciences/sciencebeam-issues/issues/124
This implements optional char lstm dropout.
=> char lstm dropout

README.md, sciencebeam_trainer_delft/sequence_labelling/tag_formatter.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/utils.py, tests/sequence_labelling/tag_formatter_test.py
part of https://github.com/elifesciences/sciencebeam-issues/issues/125
=> implemented tag data_unidiff

README.md, sciencebeam_trainer_delft/sequence_labelling/config.py, sciencebeam_trainer_delft/sequence_labelling/engines/wapiti_adapters.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/cli.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/cli_args.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/utils.py, sciencebeam_trainer_delft/sequence_labelling/trainer.py, sciencebeam_trainer_delft/sequence_labelling/utils/checkpoints.py, sciencebeam_trainer_delft/sequence_labelling/utils/train_notify.py, sciencebeam_trainer_delft/utils/keras/callbacks.py, tests/sequence_labelling/utils/checkpoints_test.py, tests/utils/keras/callbacks_test.py
part of https://github.com/elifesciences/sciencebeam-issues/issues/8
=> implemented --auto-resume

sciencebeam_trainer_delft/sequence_labelling/preprocess.py
Improved memory efficiency when fitting feature preprocessor by using generator.
Also added additional logging, including progress while fitting.
=> improved memory efficiency when fitting feature preprocessor

README.md, sciencebeam_trainer_delft/sequence_labelling/tagger.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/cli.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/cli_args.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/utils.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py, tests/sequence_labelling/tagger_test.py, tests/sequence_labelling/tools/grobid_trainer/utils_test.py
This helps to look at the raw model predictions (after unrolling), as well as what the expected value after transformation is.
=> implemented --tag-transformed

Jenkinsfile
part of https://github.com/elifesciences/sciencebeam-issues/issues/181
When pushing to testpy both for PRs and mainline, the same version may be created. Causing it to fail when creating a tag release. In that case there is no need to push to testpypi.
=> push to testpypi only for pr

scripts/dev/push-pypi-version.sh
part of https://github.com/elifesciences/sciencebeam-issues/issues/181
The version wasn't updated package built.
(In `sciencebeam-alignment` that was done as part of the Docker build)
=> fixed push to pypi

README.md
part of https://github.com/elifesciences/sciencebeam-issues/issues/237
=> updated readme to mention change of stewardship
