Makefile, sciencebeam_trainer_delft/download_manager.py, sciencebeam_trainer_delft/embedding_manager.py, sciencebeam_trainer_delft/grobid_trainer.py, tests/download_manager_test.py, tests/embedding_manager_test.py, tests/grobid_trainer_test.py
allows to specify for example:
```bash
--input https://github.com/elifesciences/sciencebeam-datasets/releases/download/v0.0.1/delft-grobid-header-060518.train.gz
```
Which will automatically unzip the file.
=> support external training data

Makefile
missed adding dependency on `.grobid-train-header-args`
=> fixed grobid-train-header args

sciencebeam_trainer_delft/download_manager.py, sciencebeam_trainer_delft/utils.py
especially useful for the very large embeddings (so that they might even fit below the 2GB threshold)
=> added lzma xz support

sciencebeam_trainer_delft/wrapper.py, tests/wrapper_test.py
since `embedding_registry_path` was not passed in, it was `None`
=> fixed default embedding manager registry path

Dockerfile.grobid, docker-compose.override.yml
data is now at /data which makes it easier to mount (without having to remember the specific sub-folder).
It's now also declared as a VOLUME.
=> moved data directory to the root

sciencebeam_trainer_delft/embedding/manager.py, tests/embedding/manager_test.py
The _ensure embedding available_ functionality used a different route, which didn't support urls pointing to an LMDB cache and as such just assumed it was the source file.
=> fixed ensure available support for mdb lmdb cache

Makefile
The `grobid_trainer` package has been moved which wasn't reflected in the `Makefile`.
=> fixed grobid_trainer package name in makefile

Dockerfile, Dockerfile.grobid
The `MANIFEST.in` file is required when submitting jobs to the cloud (e.g. training)
=> added missing manifest.in to image

Dockerfile, Dockerfile.grobid, notebooks/train-header.ipynb, requirements.build.txt, requirements.cpu.txt
regarding the security issue [GHSA-977j-xj7q-2jr9
](https://github.com/elifesciences/sciencebeam-trainer-delft/network/alert/requirements.cpu.txt/tensorflow/open)
=> bumps tensorflow to >=1.15.1,<2.0.0

sciencebeam_trainer_delft/utils/download_manager.py, tests/utils/download_manager_test.py
previously it would have treated `http://host1/file` and `http://host2/file` the same and wouldn't download the file, thinking it already had downloaded it. This now adds the md5 of the URL to the local filename, therefore the local filename will be different.
=> use md5 in downloaded files to avoid basename collision

sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py
In other modes, the embedding will be loaded from the model config. Therefore it doesn't make sense to validate the passed in embedding.
=> only validate embedding in train mode

sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/saving.py
this is necessary to be able to separate logging from command output (e.g. tagging output)
=> suppressing non-eval print statements

sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py
the separator is actually a hyphen rather than a colon
=> fixed feature indices help message

README.md, sciencebeam_trainer_delft/sequence_labelling/engines/wapiti.py, sciencebeam_trainer_delft/sequence_labelling/engines/wapiti_adapters.py, sciencebeam_trainer_delft/sequence_labelling/engines/wapiti_install.py, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py
This allow running the training in AI platform and install Wapiti on demand. It can also be used to try different versions of Wapiti.
(In the future it might get replaced with a more tight integration as a library - if it seems worth it)
=> install wapiti from source

sciencebeam_trainer_delft/sequence_labelling/data_generator.py, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py
resolves https://github.com/elifesciences/issues/issues/5577
related to https://github.com/elifesciences/sciencebeam-trainer-delft/pull/142
Evaluation should not use the same max sequence length
=> added eval max sequence length for train_eval

README.md, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/tagger.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py
Because evaluation may not apply the maximum sequence length used for training, a smaller batch size was required to not run out of memory.
=> added --eval-batch-size argument

sciencebeam_trainer_delft/sequence_labelling/__init__.py, sciencebeam_trainer_delft/utils/sklearn_externals_patch.py, tests/sequence_labelling/__init__.py
sklearn 0.23.0 no longer has `sklearn.externals.joblib` which would fail, because delft 0.5.6 is using it.
=> patch sklearn externals joblib (temporarily)

Dockerfile.grobid
this caused preloaded embeddings to be downloaded again (due to the changing working directory and using a relative `data` directory)
=> added link to /data from /opt/grobid

Dockerfile.grobid
the volume declaration prevented adding files to /data at build time
=> removed volume declaration from Dockerfile

requirements.txt
keras-bert 0.85.0 requires Keras 2.4.3.
That should get upgraded separated and tested more thouroughly.
=> downgraded keras-bert to <0.85.0

sciencebeam_trainer_delft/sequence_labelling/evaluation.py, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, tests/sequence_labelling/evaluation_test.py
By adding the `--eval-first-entity`, it will additionally evaluate the first item of all of the entities. e.g. `first_<author>` or `first_<reference>`. That is in particular useful to check whether the model found the first item well.
=> add --eval-first-entity

sciencebeam_trainer_delft/sequence_labelling/config.py, sciencebeam_trainer_delft/sequence_labelling/data_generator.py, sciencebeam_trainer_delft/sequence_labelling/tagger.py, sciencebeam_trainer_delft/sequence_labelling/trainer.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py, tests/sequence_labelling/data_generator_test.py
improvement of #235
This should be more efficient and using less memory.
In the previous version, the chars would have been padded with `<PAD>` for as many times as the maximum number of tokens in the batch. To be able to still load the old model, there is a temporary backward compatibility.
The backward compatibility is enabled, if the model version is below `2`. The model version is a field in the model config (which will be the latest version whenever a new model is trained).
=> refactor data generator text feature

requirements.txt, sciencebeam_trainer_delft/sequence_labelling/features_preprocess.py, sciencebeam_trainer_delft/sequence_labelling/preprocess.py, sciencebeam_trainer_delft/sequence_labelling/saving.py, sciencebeam_trainer_delft/utils/io.py, sciencebeam_trainer_delft/utils/json.py, tests/sequence_labelling/saving_test.py
This more or less reflects the implementation in https://github.com/kermitt2/delft/pull/105
Although with the added complexity that it needs to support different preprocessors and that the `FeaturesPreprocessor` is not JSON serializable out of the box.
It aims to be backward compatible by loading the pickle if the JSON file wasn't found. It will save both JSON and pickle, in case there is an issue with the JSON. It is using `jsonpickle`, i.e. the JSON is not just the plain properties. But it could potentially be converted.
part of https://github.com/elifesciences/issues/issues/5952 to already have the JSON available.
=> added json preprocessor support

sciencebeam_trainer_delft/sequence_labelling/preprocess.py
#257 broke loading the original pickle files with the following exception:
```
File "/opt/sciencebeam-trainer-delft/sciencebeam_trainer_delft/sequence_labelling/preprocess.py", line 120, in __setstate__
self.vectorizer.feature_names_ = state['vectorizer.feature_names']
KeyError: 'vectorizer.feature_names'
```
This is because the expected state had changed (which is also used for the JSON serialization). This change adds backward compatibility for loading the previously generated pickle files.
=> added support for original preprocessor pickle

sciencebeam_trainer_delft/sequence_labelling/config.py, sciencebeam_trainer_delft/sequence_labelling/data_generator.py, sciencebeam_trainer_delft/sequence_labelling/reader.py, sciencebeam_trainer_delft/sequence_labelling/tagger.py, sciencebeam_trainer_delft/sequence_labelling/trainer.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py, sciencebeam_trainer_delft/utils/progress_logger.py
part of https://github.com/elifesciences/issues/issues/6057
One of the main contributors was `np.asarray` without a `dtype`, which may have resulted in 1 GB instead of 20 MB for the features array, which consists of many small strings (often just one character).
=> reduce memory consumption

README.md, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/tagger.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py, tests/sequence_labelling/tagger_test.py
part of https://github.com/elifesciences/issues/issues/6057
With the currently used Keras version, stateful LSTM are also very slow at prediction time. This offers an alternative for stateless models (the default). In that case a window overlap would be advisable.
=> implemented stateless window stride

sciencebeam_trainer_delft/sequence_labelling/reader.py
part of https://github.com/elifesciences/sciencebeam-issues/issues/58
extension of #274
a memory usage improvement that was applied to `load_data_and_labels_crf_lines` hadn't been applied to `load_data_crf_lines`.
=> improve memory usage of load_data_crf_lines

sciencebeam_trainer_delft/sequence_labelling/tagger.py, tests/sequence_labelling/tagger_test.py
GROBID might pass an empty input to the model. That caused the tagging to throw an exception.
This PR will at least fix it on the Python side and respond with an empty response.
=> fixed tagging fails with empty input

Makefile, README.md, notebooks/train-header.ipynb, sciencebeam_trainer_delft/sequence_labelling/config.py, sciencebeam_trainer_delft/sequence_labelling/grobid_trainer.py, sciencebeam_trainer_delft/sequence_labelling/models.py, sciencebeam_trainer_delft/sequence_labelling/preprocess.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py, tests/sequence_labelling/config_test.py, tests/sequence_labelling/grobid_trainer_test.py, tests/sequence_labelling/models_test.py, tests/sequence_labelling/preprocess_test.py, tests/sequence_labelling/saving_test.py
part of https://github.com/elifesciences/sciencebeam-issues/issues/73
The arguments `--feature-indices` and `--feature-embedding-size` were not properly passed in. That is because some of the code was adopted upstream but with a slightly different name (`features` instead of `feature`). In attempting to make it compatible, this wasn't properly passed in. The tests didn't catch that.
This PR fixes that, it also changes most reference to the name used upstream to avoid confusion. It should still be backwards compatible with previous models.
=> fixed feature indices not passed on

Jenkinsfile, Makefile
The Jenkins build is currently quite slow.
This is an attempt to speed things up by running some independent builds in parallel.
=> configure Jenkins to run builds in parallel

requirements.txt
The new version of gensim is causing the following issue in combination with the other dependencies (in particular `numpy`):
```text
ERROR   2021-03-26 11:35:42 +0000       service         Traceback (most recent call last):
ERROR   2021-03-26 11:35:42 +0000       service           [...]
ERROR   2021-03-26 11:35:42 +0000       service           File "/root/.local/lib/python3.7/site-packages/sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/cli.py", line 29, in <module>
ERROR   2021-03-26 11:35:42 +0000       service             from sciencebeam_trainer_delft.sequence_labelling.utils.train_notify import (
ERROR   2021-03-26 11:35:42 +0000       service           File "/root/.local/lib/python3.7/site-packages/sciencebeam_trainer_delft/sequence_labelling/utils/train_notify.py", …
```
=> set upper limit for gensim due to incompatibility

sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/utils.py
The input data is already shuffle when `--shuffle-input` was specified.
Shuffling additionally without specifying the seed may make the split less predictable.
=> disabled train test split shuffle

sciencebeam_trainer_delft/sequence_labelling/config.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/cli.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/cli_args.py, sciencebeam_trainer_delft/sequence_labelling/trainer.py
For small models / datasets, it might be better to have a larger gap between checkpoints.
This just passes the `--checkpoint-epoch-interval` value on as the `period` value to `ModelCheckpoint`.
=> added --checkpoint-epoch-interval

sciencebeam_trainer_delft/sequence_labelling/models.py
Specifying stateful on the char lstm doesn't seem to make sense (if enabled globally).
It was really just meant to be for the word level lstm.
(perhaps that would make it slightly faster)
=> removed char lstm statefulness

README.md, sciencebeam_trainer_delft/sequence_labelling/tag_formatter.py, sciencebeam_trainer_delft/sequence_labelling/tagger.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/utils.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py, tests/sequence_labelling/tag_formatter_test.py
part of https://github.com/elifesciences/sciencebeam-issues/issues/125
This streams the tag results, so that results are displayed sooner and it doesn't increase the memory for at least the tagging result (the input data is still read into memory in full).
=> stream tag result to stdout

README.md, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/cli.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/cli_args.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/utils.py, sciencebeam_trainer_delft/utils/io.py
part of https://github.com/elifesciences/sciencebeam-issues/issues/125
It may be more convenient to explicitly specify an output file rather than redirecting stdout.
In particular, this can be helpful when running on a remote vm (cloud) and saving it to cloud storage.
=> added support for --tag-output-path

README.md, sciencebeam_trainer_delft/sequence_labelling/config.py, sciencebeam_trainer_delft/sequence_labelling/models.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/cli.py, sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/cli_args.py, sciencebeam_trainer_delft/utils/cli.py
The `segmentation` model with the additional text feature may end up having a lot of padding characters.
This allows the `mask_zero` feature to be used.
=> added --char-input-mask-zero

sciencebeam_trainer_delft/sequence_labelling/tools/grobid_trainer/utils.py
When using the tag sub command, it may be common to pipe it to `head`.
In that case we would receive a `BrokenPipeError` that should be ignored (program should end).
=> ignore broken pipe error on tag sub command

README.md, sciencebeam_trainer_delft/sequence_labelling/dataset_transform/unroll_transform.py, sciencebeam_trainer_delft/sequence_labelling/tag_formatter.py, sciencebeam_trainer_delft/sequence_labelling/wrapper.py, tests/sequence_labelling/data_transform/unroll_transform_test.py, tests/sequence_labelling/tools/grobid_trainer/utils_test.py
fix for #385
for numpy arrays the line status was added to each feature instead of as an additional column.
also changed behaviour to use beginning prefix if tag has changed.
=> fixed unroll text feature

sciencebeam_trainer_delft/sequence_labelling/wrapper.py
the transformed dataset was passed to the preprocessor, but the trainer received the original train and valid dataset.
=> fixed transformed dataset not passed to trainer

sciencebeam_trainer_delft/sequence_labelling/wrapper.py
The tagger is already doing the transformation. Therefore the evaluation method shouldn't do the transformation as well.
=> fixed evaluation with unrolled features

sciencebeam_trainer_delft/sequence_labelling/tag_formatter.py, tests/sequence_labelling/tag_formatter_test.py
part of https://github.com/elifesciences/sciencebeam-issues/issues/154
=> fixed iter_to_data_lines to separate documents

.gitignore, Dockerfile, Dockerfile.grobid, Jenkinsfile, Makefile, requirements.dev.txt, sciencebeam_trainer_delft/__init__.py, scripts/dev/get-commit-version.sh, scripts/dev/print-version.sh, scripts/dev/push-pypi-version.sh, scripts/dev/push-testpypi-commit-version.sh, scripts/dev/set-version.sh, scripts/dev/verify-version.sh, setup.py
part of https://github.com/elifesciences/sciencebeam-issues/issues/181
This pushes the package to testpypi (on every PR) and main pypi on tag release.
It uses the slightly verbose approach previously used by `sciencebeam-alignment`. It works for a Dockerized project.
There would be alternatives when using GitHub Actions.
One additional challenge is that we have a dependency on `delft` but do not want all of its requirements (e.g. TensorFlow version).
=> create pypi release
